"use client";
import {useEffect,useMemo,useState} from 'react';
import resourcesData from '@/knowledge/resources.json';
import {solveProject} from '@/src/solver/solve';
import type {Language,ProjectInput,Solution} from '@/src/solver/types';

const nextWeek=()=>new Date(Date.now()+7*86400000).toISOString().slice(0,10);
const initial:ProjectInput={brief:'I need a projected installation where hand movement grows procedural flowers. TouchDesigner is required.',deadline:nextWeek(),hoursPerDay:2,skills:'Blender — intermediate; TouchDesigner — basics; DaVinci Resolve — basic editing',constraints:'Must use TouchDesigner. Final output must be interactive.',language:'en'};
const ui={
 en:{headline:'Finish the project.',accent:'Skip the detours.',lede:'QUANDA evaluates viable production routes, resolves every technique to a concrete app, and gives you one defensible path to done.',make:'What are you trying to make?',deadline:'Deadline',time:'Hours / day',skills:'What do you already know?',constraints:'Non-negotiable constraints',solve:'Find my best path',recommended:'Your best path',why:'Why this path won',capacity:'Available capacity',human:'Human time',learning:'New learning',agent:'Agent time',steps:'Execution steps',alternatives:'Other viable paths considered',skipped:'QUANDA skipped',diagnostics:'Solver diagnostics',edit:'Edit brief',fit:'Deadline fit',done:'Definition of done',reason:'Why included',resources:'Evidence & resources',none:'No suitable verified resource found',error:'Add a little more detail so QUANDA can make a defensible decision.',proof:'Most efficient route among the evaluated viable options.',method:'Deterministic local solver · no live web search',day:'days',min:'min',examples:['Installation','3D animation','Creative coding','Three.js portfolio'],briefs:['TouchDesigner is mandatory. I know TOPs and CHOPs. Webcam hand tracking must control flower growth in a projected installation.','I know Blender modelling and keyframes. I need a cel-shaded product animation and do not want another 3D package.','I know Illustrator but have never coded. I want a Bauhaus poster where shapes react to music.','I need an interactive Three.js portfolio. I know basic HTML/CSS, have Codex, and only 3 days.']},
 vi:{headline:'Hoàn thành dự án.',accent:'Bỏ qua đường vòng.',lede:'QUANDA đánh giá các lộ trình sản xuất khả thi, gắn mọi kỹ thuật với ứng dụng cụ thể và đưa ra một đường đi có cơ sở đến đích.',make:'Bạn đang muốn tạo gì?',deadline:'Hạn chót',time:'Giờ / ngày',skills:'Bạn đã biết công cụ nào?',constraints:'Các ràng buộc bắt buộc',solve:'Tìm lộ trình tốt nhất',recommended:'Lộ trình tốt nhất',why:'Vì sao lộ trình này thắng',capacity:'Quỹ thời gian',human:'Thời gian của bạn',learning:'Cần học mới',agent:'Thời gian agent',steps:'Các bước thực hiện',alternatives:'Lộ trình khả thi khác đã xét',skipped:'QUANDA đã bỏ qua',diagnostics:'Chẩn đoán solver',edit:'Sửa brief',fit:'Khớp deadline',done:'Điều kiện hoàn thành',reason:'Vì sao có bước này',resources:'Bằng chứng & tài nguyên',none:'Không tìm thấy tài nguyên đã kiểm chứng phù hợp',error:'Hãy thêm chi tiết để QUANDA đưa ra quyết định có cơ sở.',proof:'Lộ trình hiệu quả nhất trong các phương án khả thi đã đánh giá.',method:'Solver local tất định · không tìm web trực tiếp',day:'ngày',min:'phút',examples:['Installation','Animation 3D','Creative coding','Portfolio Three.js'],briefs:['TouchDesigner là bắt buộc. Tôi biết TOPs và CHOPs. Hand tracking webcam phải điều khiển hoa mọc trong installation trình chiếu.','Tôi biết modelling và keyframe trong Blender. Tôi cần animation cel-shaded và không muốn học thêm phần mềm 3D.','Tôi biết Illustrator nhưng chưa từng code. Tôi muốn poster Bauhaus có các hình phản ứng với âm nhạc.','Tôi cần portfolio Three.js tương tác. Tôi biết HTML/CSS cơ bản, có Codex và chỉ còn 3 ngày.']}
};
const format=(n:number,l:Language)=>n<60?`${n} ${ui[l].min}`:`${Math.floor(n/60)}h${n%60?` ${n%60}m`:''}`;

export default function QuandaApp(){
 const [input,setInput]=useState<ProjectInput>(initial),[solution,setSolution]=useState<Solution|null>(null),[error,setError]=useState('');const l=input.language,c=ui[l];
 useEffect(()=>{const saved=localStorage.getItem('quanda-v2-draft');if(!saved)return;const timer=window.setTimeout(()=>{try{setInput({...initial,...JSON.parse(saved)})}catch{}},0);return()=>window.clearTimeout(timer)},[]);
 useEffect(()=>{localStorage.setItem('quanda-v2-draft',JSON.stringify(input))},[input]);
 const resources=useMemo(()=>Object.fromEntries(resourcesData.resources.map((r)=>[r.id,r])),[]);
 const update=<K extends keyof ProjectInput>(key:K,value:ProjectInput[K])=>setInput((v)=>({...v,[key]:value}));
 const run=()=>{if(input.brief.trim().length<18){setError(c.error);return}setError('');setSolution(solveProject(input));setTimeout(()=>document.getElementById('result-top')?.focus(),0)};
 const example=(i:number)=>{update('brief',c.briefs[i]);if(i===0){update('skills','Blender — intermediate; TouchDesigner — basics; DaVinci Resolve — basic');update('constraints',l==='vi'?'Bắt buộc dùng TouchDesigner. Đầu ra phải tương tác.':'TouchDesigner is mandatory. Final output must be interactive.')}if(i===1){update('skills','Blender — modelling, materials, lighting, keyframes');update('constraints','Do not introduce another 3D package.')}if(i===2){update('skills','Illustrator — advanced; Coding — none');update('constraints','Prefer free tools.')}if(i===3){update('skills','HTML/CSS — basic; JavaScript — beginner; Codex — available');update('constraints','Must run in browser and deploy to Vercel.')}};
 return <main><nav className="nav"><button className="brand" onClick={()=>setSolution(null)}><b>Q</b> QUANDA <sup>V2</sup></button><div><span className="verified">● Evidence-backed</span><button className="lang" onClick={()=>update('language',l==='en'?'vi':'en')}>EN / VI</button></div></nav>
 {!solution?<><section className="hero"><div className="hero-copy"><p className="eyebrow">01 · Creative pipeline solver</p><h1>{c.headline}<br/><em>{c.accent}</em></h1><p className="lede">{c.lede}</p><div className="examples">{c.examples.map((x,i)=><button key={x} onClick={()=>example(i)}>{x}</button>)}</div></div><form className="brief" onSubmit={(e)=>{e.preventDefault();run()}}><label>{c.make}<textarea value={input.brief} onChange={(e)=>update('brief',e.target.value)} aria-invalid={!!error}/></label><div className="fields"><label>{c.deadline}<input type="date" value={input.deadline} onChange={(e)=>update('deadline',e.target.value)}/></label><label>{c.time}<input type="number" min=".5" max="16" step=".5" value={input.hoursPerDay} onChange={(e)=>update('hoursPerDay',Number(e.target.value))}/></label></div><label>{c.skills}<input value={input.skills} onChange={(e)=>update('skills',e.target.value)}/></label><label>{c.constraints}<input value={input.constraints} onChange={(e)=>update('constraints',e.target.value)}/></label>{error&&<p role="alert" className="error">{error}</p>}<button className="primary">{c.solve}<span>→</span></button><small>{c.method}</small></form></section><section className="strip">{[['01','Understand','Destination + constraints'],['02','Resolve','Technique → software'],['03','Evaluate','Viable paths + proof'],['04','Execute','Production-ready tasks']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</section></>:
 <section className="results"><header className="result-head"><div><p className="eyebrow">02 · {c.recommended}</p><h1 id="result-top" tabIndex={-1}>{solution.recommended.title}</h1><p>{c.proof}</p></div><button className="secondary" onClick={()=>setSolution(null)}>← {c.edit}</button></header><div className="top-grid"><article className="recommend"><div className="score"><b>{solution.recommended.score}</b><span>/100</span></div><div className="route">{solution.recommended.softwareLabels.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b>{i<solution.recommended.softwareLabels.length-1&&<i>→</i>}</div>)}</div><p>The route is scored from requirements, familiarity, time, switching cost, resources, and risk.</p><div className="metrics">{[[c.capacity,format(solution.capacityMinutes,l),`${solution.daysAvailable} ${c.day}`],[c.human,format(solution.recommended.estimatedHumanMinutes,l),''],[c.learning,format(solution.recommended.estimatedLearningMinutes,l),''],[c.agent,format(solution.recommended.estimatedAgentMinutes,l),'']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</div></article><aside className="why"><h2>{c.why}</h2><ul>{solution.recommended.strengths.map(x=><li key={x}><span>✓</span>{x}</li>)}</ul><div className="fit"><span>{c.fit}</span><b>{solution.recommended.scoreBreakdown.deadlineFit}%</b><i><em style={{width:`${solution.recommended.scoreBreakdown.deadlineFit}%`}}/></i></div>{solution.requirements.length>0&&<p><b>Required:</b> {solution.requirements.join(', ')}</p>}{solution.knownSoftware.length>0&&<p><b>Known:</b> {solution.knownSoftware.join(', ')}</p>}</aside></div>
 <section className="steps"><p className="eyebrow">03 · {c.steps}</p>{solution.recommended.tasks.map((task,i)=>{const rr=task.resourceIds.map(id=>resources[id]).filter(Boolean);return <article className="task" key={task.id}><div className="num">{String(i+1).padStart(2,'0')}</div><div className="task-body"><header><div><span>{task.softwareLabel} · {task.methodLabel}</span><h3>{task.title}</h3></div><b>{format(task.estimatedHumanMinutes+task.estimatedLearningMinutes,l)}</b></header><p>{task.objective}</p><div className="tags">{task.techniqueIds.map(id=><code key={id}>{id.split('.').at(-1)}</code>)}</div><details><summary>{c.done} + {c.reason}</summary><div className="detail"><div><b>{c.reason}</b><p>{task.whyIncluded}</p></div><div><b>{c.done}</b><ul>{task.definitionOfDone.map(x=><li key={x}>{x}</li>)}</ul></div><div><b>{c.resources}</b>{rr.length?rr.map(r=><a key={r.id} href={r.url} target="_blank" rel="noreferrer">{r.title} ↗<small>{r.reliability} · {r.language.toUpperCase()}</small></a>):<p className="none">{c.none}</p>}</div></div></details></div></article>})}</section>
 <div className="proof-grid"><section className="alternatives"><p className="eyebrow">04 · {c.alternatives}</p>{solution.alternatives.map((p,i)=><details key={p.id}><summary><span>#{i+2}</span><b>{p.title}</b><em>{p.score}</em></summary><p>{(p.weaknesses.length?p.weaknesses:p.strengths).join(' · ')}</p></details>)}</section><section className="skipped"><p className="eyebrow">05 · {c.skipped}</p><ul>{solution.skipped.map(x=><li key={x}><span>×</span>{x}</li>)}</ul></section></div><details className="diagnostics"><summary>{c.diagnostics}</summary><pre>{JSON.stringify({detectedKind:solution.detectedKind,requirements:solution.requirements,knownSoftware:solution.knownSoftware,rejectedPaths:solution.rejected.map(p=>({id:p.id,reasons:p.rejectionReasons})),scoreBreakdown:solution.recommended.scoreBreakdown,solverVersion:solution.solverVersion,scoringVersion:solution.scoringVersion},null,2)}</pre></details></section>}
 <footer><span>QUANDA evaluates viable paths. It does not promise a global optimum.</span><span>24,870 ontology concepts · {resourcesData.resourceCount} migrated resources</span></footer></main>
}
